---
version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - /media/usbdisk/music:/music
      - /media/usbdisk/movies:/movies
      - /home/ubuntu/tv:/tv
      - /media/usbdisk/HomeMovies:/HomeMovies
      - /media/usbdisk/config:/config
    restart: unless-stopped
  api:
    image: api
    container_name: api
    network_mode: host
    restart: unless-stopped
